(async function(){
  const runtime=window.LMI_RUNTIME={user:null,session:null,apps:[],desktopState:null};
  const $=id=>document.getElementById(id);
  function setStatus(txt,cls=''){ const el=$('loginStatus'); if(el){el.textContent=txt; el.className='login-status '+cls;} }
  function getInstalled(){ try{return JSON.parse(localStorage.getItem(LMI_CONFIG.localKeys.installed)||'null')}catch{return null} }
  function setInstalled(ids){ localStorage.setItem(LMI_CONFIG.localKeys.installed,JSON.stringify(ids)); }
  function getLayout(){ try{return JSON.parse(localStorage.getItem(LMI_CONFIG.localKeys.layout)||'{}')}catch{return {}} }
  function saveLayout(o){ localStorage.setItem(LMI_CONFIG.localKeys.layout,JSON.stringify(o||{})); }
  function themeVars(){ try{return JSON.parse(localStorage.getItem('LMI_THEME_VARS')||'{}')}catch{return {}} }
  function applyTheme(vars){ vars=vars||themeVars(); Object.entries(vars).forEach(([k,v])=>{ if(k.startsWith('--')) document.documentElement.style.setProperty(k,String(v)); }); document.body.dataset.themeLive='1'; }
  function applyWallpaper(user){ const desk=document.querySelector('.desktop'); const wp=user?.wallpaper||user?.wp||localStorage.getItem('LMI_WALLPAPER')||''; if(wp){document.documentElement.style.setProperty('--wallpaper-url',`url("${wp}")`); desk?.classList.add('wallpapered')}else desk?.classList.remove('wallpapered'); }
  window.LMI_DESKTOP={
    getSavedWindow(id){return getLayout()[id]||null},
    saveWindow(id,data){const l=getLayout(); l[id]=Object.assign({},l[id]||{},data); saveLayout(l); if(runtime.session?.mode==='relay') LMI_API.callRelay('saveDesktopLayout',{appId:id,layout:data},runtime.user).catch(()=>{});},
    refreshApps:renderDesktop,
    getApps(){return runtime.apps||[];}
  };
  async function loadManifest(){ try{ const res=await fetch(LMI_CONFIG.manifestPath,{cache:'no-store'}); if(res.ok)return await res.json(); }catch{} return []; }
  function normalizeApp(a){return {id:a.id||a.appId, key:a.key||a.k, name:a.name||a.nm||a.id, title:a.title||a.name||a.nm, path:a.path||a.modulePath, icon:a.icon||a.ico||'□', description:a.description||a.desc||'', w:Number(a.w||a.defaultW||900), h:Number(a.h||a.defaultH||620), x:Number(a.x||80), y:Number(a.y||70), iconX:Number(a.iconX||0), iconY:Number(a.iconY||0)} }
  function visibleApps(){ const installed=(runtime.session?.mode==='relay')?null:getInstalled(); return runtime.apps.filter(a=>!installed||installed.includes(a.id)||['settings','bipac','themeLab','dataEditor'].includes(a.id)); }
  function renderDesktop(){ const desk=$('desktopIcons'); if(!desk)return; desk.innerHTML=''; visibleApps().forEach((app,i)=>{ const b=document.createElement('button'); b.className='desktop-icon'; b.dataset.app=app.id; b.style.left=(Number(app.iconX)||((i%6)*145+36))+'px'; b.style.top=(Number(app.iconY)||(Math.floor(i/6)*145+72))+'px'; b.innerHTML=`<span class="icon-box">${app.icon||'□'}</span><strong>${app.name}</strong><em>${app.description||''}</em>`; let moved=false, downAt=0; b.addEventListener('pointerdown',ev=>{ if(ev.button!==0)return; moved=false; downAt=Date.now(); b.setPointerCapture(ev.pointerId); const r=b.getBoundingClientRect(), wr=$('desktopIcons').getBoundingClientRect(); const ox=ev.clientX-r.left, oy=ev.clientY-r.top; function mv(e){ const x=Math.max(0,Math.min(wr.width-112,e.clientX-wr.left-ox)); const y=Math.max(0,Math.min(wr.height-120,e.clientY-wr.top-oy)); if(Math.abs(x-r.left+wr.left)>3||Math.abs(y-r.top+wr.top)>3)moved=true; b.style.left=x+'px'; b.style.top=y+'px'; } function up(e){ b.releasePointerCapture(ev.pointerId); b.removeEventListener('pointermove',mv); b.removeEventListener('pointerup',up); if(moved){ app.iconX=parseInt(b.style.left)||0; app.iconY=parseInt(b.style.top)||0; window.LMI_DESKTOP.saveWindow(app.id,{iconX:app.iconX,iconY:app.iconY}); } } b.addEventListener('pointermove',mv); b.addEventListener('pointerup',up); }); b.ondblclick=()=>{ if(!moved) LMI_WM.openWindow(app); }; b.onclick=()=>{ if(moved||Date.now()-downAt>450)return; document.querySelectorAll('.desktop-icon').forEach(x=>x.classList.remove('selected')); b.classList.add('selected');}; desk.appendChild(b); }); renderStartMenu(); }
  function renderStartMenu(){ const sm=$('startMenu'); if(!sm)return; sm.innerHTML=visibleApps().map(app=>`<button class="start-item" data-app="${app.id}"><span class="si">${app.icon||'□'}</span><span><b>${app.name}</b><em>${app.description||''}</em></span></button>`).join('')+'<hr><button class="start-item" data-act="home"><span class="si">⌂</span><span><b>Show Desktop</b><em>Minimize open modules</em></span></button><button class="start-item" data-act="logout"><span class="si">×</span><span><b>Lock Terminal</b><em>Return to login</em></span></button>'; sm.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>{const app=runtime.apps.find(a=>a.id===b.dataset.app); if(app)LMI_WM.openWindow(app); sm.classList.add('hidden')}); sm.querySelector('[data-act="home"]').onclick=()=>{document.querySelectorAll('.lmi-window').forEach(w=>w.classList.add('minimized')); sm.classList.add('hidden')}; sm.querySelector('[data-act="logout"]').onclick=()=>location.reload(); }
  async function loadDesktopState(user){ let manifest=(await loadManifest()).map(normalizeApp); if(LMI_API.getRelayUrl()){ try{ const resp=await LMI_API.callRelay('getDesktopState',{},user); const data=(resp&&resp.data)||resp; if(data&&Array.isArray(data.apps)&&data.apps.length){ runtime.desktopState=data; runtime.user=Object.assign({},runtime.user||{},data.user||{}); { const remote=data.apps.map(normalizeApp); const byId=new Map(remote.map(a=>[a.id,a])); manifest.forEach(a=>{ if(['settings','bipac','themeLab','dataEditor'].includes(a.id) && !byId.has(a.id)) remote.push(a); }); return remote; } } }catch(e){ setStatus('Backend desktop state failed; using local manifest. '+(e.message||e),'warn'); } } return manifest; }
  async function enterDesktop(user,session){ runtime.user=user; runtime.session=session; $('operatorPlate').textContent=`Operator: ${user.displayName||user.tag} / ${user.access||'User'}`; document.body.classList.add('logged-in'); document.body.classList.remove('auth-locked'); runtime.apps=await loadDesktopState(user); if(!getInstalled()) setInstalled(runtime.apps.map(a=>a.id)); applyTheme(); applyWallpaper(runtime.user||user); renderDesktop(); updateClock(); setInterval(updateClock,1000); }
  function updateClock(){ const c=$('clock'); if(c)c.textContent=new Date().toLocaleString([], {year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'}); }
  function initLogin(){ applyTheme(); const saved=localStorage.getItem(LMI_CONFIG.localKeys.relayUrl)||''; $('relayUrl').value=saved; const last=LMI_AUTH.loadLastUser(); if(last?.tag) $('loginUsername').value=last.tag; $('saveRelay').onclick=()=>{ const url=$('relayUrl').value.trim(); if(url&&!LMI_API.isAllowedRelayUrl(url)){setStatus('Relay rejected: expected a Google Apps Script web app URL.','bad'); return;} if(url){LMI_API.setRelayUrl(url); setStatus('Relay link cached in this browser only.','good');}else{LMI_API.forgetRelayUrl(); setStatus('Relay link cleared.','warn');} }; $('forgetRelay').onclick=()=>{LMI_API.forgetRelayUrl(); $('relayUrl').value=''; setStatus('Relay link forgotten from this browser.','warn');}; $('loginButton').onclick=async()=>{ try{ if($('relayUrl').value.trim()) LMI_API.setRelayUrl($('relayUrl').value.trim()); setStatus('Reading credentials...'); const result=await LMI_AUTH.login($('loginUsername').value,$('loginPassword').value); setStatus('Credential accepted.','good'); enterDesktop(result.user,result.session); }catch(e){ setStatus(e.message||String(e),'bad'); } }; $('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter') $('loginButton').click();}); $('relayUrl').addEventListener('keydown',e=>{if(e.key==='Enter') $('saveRelay').click();}); $('startBtn')?.addEventListener('click',()=>{$('startMenu')?.classList.toggle('hidden')}); document.addEventListener('click',e=>{ if(!e.target.closest('.taskbar')) $('startMenu')?.classList.add('hidden'); }); }
  window.addEventListener('message',async event=>{ if(event.origin!==location.origin) return; const msg=event.data||{}; if(msg.type==='LMI_REQUEST_CONTEXT'){ event.source.postMessage({type:'LMI_CONTEXT',requestId:msg.requestId,context:{user:runtime.user,session:runtime.session,hasRelay:!!LMI_API.getRelayUrl(),apps:runtime.apps}},event.origin); } if(msg.type==='LMI_API_REQUEST'){ try{ const data=await LMI_API.callRelay(msg.action,msg.payload,runtime.user); event.source.postMessage({type:'LMI_API_RESPONSE',requestId:msg.requestId,ok:true,data},event.origin); } catch(e){ event.source.postMessage({type:'LMI_API_RESPONSE',requestId:msg.requestId,ok:false,error:e.message||String(e)},event.origin); } } if(msg.type==='LMI_SET_RELAY_URL'){ const url=String(msg.url||'').trim(); if(url&&!LMI_API.isAllowedRelayUrl(url)){event.source.postMessage({type:'LMI_RELAY_URL_STATUS',ok:false,message:'Rejected relay URL.'},event.origin);return;} if(url)LMI_API.setRelayUrl(url); else LMI_API.forgetRelayUrl(); event.source.postMessage({type:'LMI_RELAY_URL_STATUS',ok:true,message:url?'Relay saved locally.':'Relay cleared.'},event.origin); } if(msg.type==='LMI_REFRESH_APPS'){ renderDesktop(); } if(msg.type==='LMI_THEME_PATCH'){ localStorage.setItem('LMI_THEME_VARS',JSON.stringify(msg.vars||{})); applyTheme(msg.vars||{}); document.querySelectorAll('.win-frame').forEach(fr=>fr.contentWindow?.postMessage({type:'LMI_THEME_PATCH',vars:msg.vars||{}},location.origin)); } });
  document.addEventListener('DOMContentLoaded',initLogin);
})();